"""PDF report generator using fpdf2 (pure Python, no system dependencies)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from fpdf import FPDF, XPos, YPos

# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------

def _t(text: object, maxlen: int = 0) -> str:
    """Convert to string and strip non-latin-1 characters (core fonts limitation).

    Replaces em-dash/en-dash with hyphens, then drops any remaining
    characters outside the latin-1 range so fpdf2 doesn't raise.
    """
    s = str(text) if text is not None else ""
    s = s.replace("\u2014", "-").replace("\u2013", "-").replace("\u2019", "'").replace("\u2018", "'")
    s = s.encode("latin-1", errors="ignore").decode("latin-1")
    if maxlen and len(s) > maxlen:
        s = s[:maxlen - 1] + "+"
    return s


# ---------------------------------------------------------------------------
# Colour palette (RGB tuples)
# ---------------------------------------------------------------------------
_C_PAGE_BG = (248, 250, 252)
_C_HEADER_BG = (30, 41, 59)
_C_WHITE = (255, 255, 255)
_C_SECTION_BG = (241, 245, 249)
_C_BORDER = (226, 232, 240)
_C_TEXT = (30, 41, 59)
_C_MUTED = (100, 116, 139)

_C_CRITICAL = (220, 38, 38)
_C_HIGH = (234, 88, 12)
_C_MEDIUM = (217, 119, 6)
_C_LOW = (101, 163, 13)
_C_PASS = (22, 163, 74)
_C_FAIL = (220, 38, 38)
_C_NA = (100, 116, 139)
_C_MANUAL = (133, 77, 14)
_C_CMD_BG = (240, 253, 244)
_C_CMD_BORDER = (22, 163, 74)

_SEV_COLORS: dict[str, tuple] = {
    "critical": _C_CRITICAL,
    "high": _C_HIGH,
    "medium": _C_MEDIUM,
    "low": _C_LOW,
    "info": (2, 132, 199),
}

_GRADE_COLORS: dict[str, tuple] = {
    "A": _C_PASS,
    "B": (101, 163, 13),
    "C": _C_MEDIUM,
    "D": _C_HIGH,
    "F": _C_CRITICAL,
}


# ---------------------------------------------------------------------------
# Main PDF class
# ---------------------------------------------------------------------------

class _FireAuditPDF(FPDF):
    """Custom FPDF subclass with FireAudit header/footer."""

    def __init__(self, report: dict) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._report = report
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(left=15, top=15, right=15)

    def header(self) -> None:
        device = self._report.get("device", {})
        hostname = device.get("hostname") or device.get("vendor", "Unknown")
        vendor = device.get("vendor", "")
        self.set_fill_color(*_C_HEADER_BG)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_C_WHITE)
        self.set_xy(15, 3)
        self.cell(130, 8, _t(f"FireAudit - {hostname} ({vendor.upper()})"), new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.set_xy(150, 3)
        self.cell(45, 8, f"Page {self.page_no()}", align="R", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_text_color(*_C_TEXT)
        self.ln(5)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_C_MUTED)
        ts = self._report.get("generated_at", "")
        self.cell(0, 8, f"Generated by FireAudit | {ts}", align="C")
        self.set_text_color(*_C_TEXT)


# ---------------------------------------------------------------------------
# Helper drawing utilities
# ---------------------------------------------------------------------------

def _section_header(pdf: FPDF, text: str) -> None:
    pdf.set_fill_color(*_C_SECTION_BG)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_C_TEXT)
    pdf.set_draw_color(*_C_BORDER)
    pdf.cell(0, 8, f"  {text}", border="B", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)


def _kv_row(pdf: FPDF, key: str, value: str, label_w: float = 45) -> None:
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*_C_MUTED)
    pdf.cell(label_w, 6, key, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_C_TEXT)
    pdf.cell(0, 6, _t(value or "-"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _sev_badge(pdf: FPDF, severity: str, x: float, y: float, w: float = 18, h: float = 5) -> None:
    color = _SEV_COLORS.get(severity.lower(), _C_MUTED)
    r, g, b = color
    # Light background: blend toward white at 15%
    bg = (int(r + (255 - r) * 0.85), int(g + (255 - g) * 0.85), int(b + (255 - b) * 0.85))
    pdf.set_fill_color(*bg)
    pdf.set_draw_color(*bg)
    pdf.set_xy(x, y)
    pdf.cell(w, h, severity.upper(), align="C", fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*color)
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 6)
    pdf.cell(w, h, severity.upper(), align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*_C_TEXT)


def _status_badge(pdf: FPDF, status: str, x: float, y: float, w: float = 16, h: float = 5) -> None:
    label_map = {
        "pass": "PASS", "fail": "FAIL", "not_applicable": "N/A",
        "manual_check": "MANUAL", "error": "ERROR",
    }
    color_map = {
        "pass": _C_PASS, "fail": _C_FAIL, "not_applicable": _C_NA,
        "manual_check": _C_MANUAL, "error": (124, 58, 237),
    }
    color = color_map.get(status, _C_MUTED)
    r, g, b = color
    bg = (int(r + (255 - r) * 0.85), int(g + (255 - g) * 0.85), int(b + (255 - b) * 0.85))
    pdf.set_fill_color(*bg)
    pdf.set_draw_color(*bg)
    pdf.set_xy(x, y)
    pdf.cell(w, h, "", fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*color)
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 6)
    pdf.cell(w, h, label_map.get(status, status.upper()), align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*_C_TEXT)


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

def _write_posture_banner(pdf: FPDF, report: dict) -> None:
    ps = report.get("posture_score", {})
    score = ps.get("score", 0)
    grade = ps.get("grade", "F")
    fail_counts = ps.get("fail_counts", {})
    color = _GRADE_COLORS.get(grade, _C_MUTED)

    # Banner box
    x0 = pdf.get_x()
    y0 = pdf.get_y()
    box_w = 180
    box_h = 28

    pdf.set_fill_color(*_C_WHITE)
    pdf.set_draw_color(*_C_BORDER)
    pdf.rect(x0, y0, box_w, box_h, "FD")

    # Grade
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*color)
    pdf.set_xy(x0 + 4, y0 + 3)
    pdf.cell(22, 22, grade, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)

    # Score number
    pdf.set_xy(x0 + 30, y0 + 4)
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(30, 12, str(score), new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_C_MUTED)
    pdf.set_xy(x0 + 60, y0 + 9)
    pdf.cell(20, 6, "/100", new_x=XPos.LMARGIN, new_y=YPos.TOP)

    # Progress bar
    bar_x = x0 + 30
    bar_y = y0 + 18
    bar_w = 110
    bar_h = 5
    pdf.set_fill_color(*_C_BORDER)
    pdf.rect(bar_x, bar_y, bar_w, bar_h, "F")
    filled_w = max(1, int(bar_w * score / 100))
    pdf.set_fill_color(*color)
    pdf.rect(bar_x, bar_y, filled_w, bar_h, "F")

    # Fail counts
    labels = [("CRIT", "critical", _C_CRITICAL), ("HIGH", "high", _C_HIGH),
              ("MED", "medium", _C_MEDIUM), ("LOW", "low", _C_LOW)]
    cx = x0 + 148
    for lbl, key, clr in labels:
        cnt = fail_counts.get(key, 0)
        pdf.set_xy(cx, y0 + 6)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*clr)
        pdf.cell(10, 5, str(cnt), align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_xy(cx, y0 + 12)
        pdf.set_font("Helvetica", "", 6)
        pdf.set_text_color(*_C_MUTED)
        pdf.cell(10, 4, lbl, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        cx += 11

    pdf.set_text_color(*_C_TEXT)
    pdf.set_xy(x0, y0 + box_h + 4)
    pdf.ln(2)


def _write_device_info(pdf: FPDF, report: dict) -> None:
    _section_header(pdf, "Device Information")
    device = report.get("device", {})
    fields = [
        ("Hostname", device.get("hostname")),
        ("Vendor", device.get("vendor")),
        ("Model", device.get("model")),
        ("Firmware", device.get("firmware_version")),
        ("Serial", device.get("serial_number")),
        ("Source File", device.get("source_file")),
        ("Config Timestamp", device.get("config_timestamp")),
    ]
    for k, v in fields:
        if v:
            _kv_row(pdf, k, str(v))
    pdf.ln(4)


def _write_summary_stats(pdf: FPDF, report: dict) -> None:
    _section_header(pdf, "Audit Summary")
    summary = report.get("summary", {})
    by_status = summary.get("by_status", {})
    by_sev = summary.get("by_severity", {})

    # Status row
    statuses = [
        ("PASS", by_status.get("pass", 0), _C_PASS),
        ("FAIL", by_status.get("fail", 0), _C_FAIL),
        ("N/A", by_status.get("not_applicable", 0), _C_NA),
        ("MANUAL", by_status.get("manual_check", 0), _C_MANUAL),
        ("ERROR", by_status.get("error", 0), (124, 58, 237)),
    ]
    col_w = 36
    x0 = pdf.get_x()
    y0 = pdf.get_y()
    for label, count, color in statuses:
        pdf.set_fill_color(*_C_WHITE)
        pdf.set_draw_color(*_C_BORDER)
        pdf.rect(x0, y0, col_w - 2, 18, "FD")
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*color)
        pdf.set_xy(x0, y0 + 2)
        pdf.cell(col_w - 2, 8, str(count), align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*_C_MUTED)
        pdf.set_xy(x0, y0 + 11)
        pdf.cell(col_w - 2, 6, label, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        x0 += col_w
    pdf.set_text_color(*_C_TEXT)
    pdf.set_xy(pdf.l_margin, y0 + 22)
    pdf.ln(4)


def _write_framework_scores(pdf: FPDF, report: dict) -> None:
    fw_scores = report.get("framework_scores", {})
    if not fw_scores:
        return

    _section_header(pdf, "Compliance Framework Scores")

    col_w = 88
    x0 = pdf.get_x()
    y0 = pdf.get_y()
    col = 0

    for fw_key, fw_data in fw_scores.items():
        pct = fw_data.get("percentage", 0)
        passed = fw_data.get("passed", 0)
        total = fw_data.get("total", 0)
        name = fw_key.replace("_", " ").upper()

        bar_color = _C_PASS if pct >= 80 else (_C_MEDIUM if pct >= 60 else _C_FAIL)

        cx = x0 + col * (col_w + 4)
        cy = y0

        pdf.set_fill_color(*_C_WHITE)
        pdf.set_draw_color(*_C_BORDER)
        pdf.rect(cx, cy, col_w, 22, "FD")
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*_C_TEXT)
        pdf.set_xy(cx + 3, cy + 3)
        pdf.cell(col_w - 6, 6, name, new_x=XPos.RIGHT, new_y=YPos.TOP)

        # Progress bar
        bx, by, bw, bh = cx + 3, cy + 11, col_w - 6, 4
        pdf.set_fill_color(*_C_BORDER)
        pdf.rect(bx, by, bw, bh, "F")
        filled = max(1, int(bw * pct / 100))
        pdf.set_fill_color(*bar_color)
        pdf.rect(bx, by, filled, bh, "F")

        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*_C_MUTED)
        pdf.set_xy(cx + 3, cy + 16)
        pdf.cell(col_w - 6, 5, f"{passed}/{total} controls  ({pct:.0f}%)", new_x=XPos.RIGHT, new_y=YPos.TOP)

        col += 1
        if col >= 2:
            col = 0
            y0 += 26
            x0 = pdf.l_margin

    if col > 0:
        y0 += 26

    pdf.set_text_color(*_C_TEXT)
    pdf.set_xy(pdf.l_margin, y0)
    pdf.ln(4)


def _write_findings(pdf: FPDF, report: dict) -> None:
    findings = report.get("findings", [])
    if not findings:
        return

    # Sort: fail first (by severity), then pass, na, manual
    sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    status_order = {"fail": 0, "error": 1, "pass": 2, "not_applicable": 3, "manual_check": 4}
    findings_sorted = sorted(
        findings,
        key=lambda f: (status_order.get(f.get("status", "pass"), 5),
                       sev_order.get(f.get("severity", "info"), 5)),
    )

    _section_header(pdf, f"Audit Findings ({len(findings_sorted)} rules)")

    # Table header
    col_widths = [22, 68, 18, 16, 56]
    headers = ["Rule ID", "Finding Name", "Severity", "Status", "Details"]
    pdf.set_fill_color(*_C_SECTION_BG)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*_C_MUTED)
    pdf.set_draw_color(*_C_BORDER)
    for header, w in zip(headers, col_widths):
        pdf.cell(w, 7, header, border="B", fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(7)

    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_C_TEXT)

    for f in findings_sorted:
        rule_id = _t(f.get("rule_id", ""))
        name = _t(f.get("name", ""), 90)
        severity = f.get("severity", "info")
        status = f.get("status", "pass")
        detail = _t(f.get("detail") or f.get("reason") or "", 220)
        remediation = _t(f.get("remediation") or "", 320)
        vendor_cmd = _t(f.get("vendor_command") or "")
        affected = [_t(a) for a in (f.get("affected_items") or [])]
        manual_note = _t(f.get("manual_note") or "", 320)

        # Estimate row height: base + multi-line content
        detail_lines = max(1, len(detail) // 50 + 1) if detail else 1
        rem_lines = max(1, len(remediation) // 60 + 1) if remediation and status == "fail" else 0
        cmd_lines = len(vendor_cmd.splitlines()) if vendor_cmd else 0
        manual_lines = max(1, len(manual_note) // 60 + 1) if manual_note else 0
        affected_lines = 1 if affected else 0
        row_h = 6 * max(1, detail_lines)
        extra_h = (rem_lines * 5 + cmd_lines * 4 + manual_lines * 5 + affected_lines * 4 +
                   (4 if remediation and status == "fail" else 0) +
                   (4 if vendor_cmd else 0) +
                   (4 if manual_note else 0))

        if pdf.get_y() + row_h + extra_h > pdf.h - 25:
            pdf.add_page()
            # Re-draw column headers on new page
            pdf.set_fill_color(*_C_SECTION_BG)
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(*_C_MUTED)
            for header, w in zip(headers, col_widths):
                pdf.cell(w, 7, header, border="B", fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.ln(7)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*_C_TEXT)

        row_y = pdf.get_y()
        x0 = pdf.l_margin

        # Draw light background on fail rows
        if status == "fail":
            pdf.set_fill_color(254, 242, 242)
            pdf.rect(x0, row_y, sum(col_widths), row_h + extra_h, "F")
        elif status == "pass":
            pdf.set_fill_color(240, 253, 244)
            pdf.rect(x0, row_y, sum(col_widths), row_h + extra_h, "F")

        # Rule ID
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*_C_TEXT)
        pdf.set_xy(x0, row_y)
        pdf.cell(col_widths[0], row_h, rule_id, new_x=XPos.RIGHT, new_y=YPos.TOP)

        # Name
        pdf.set_font("Helvetica", "", 7)
        pdf.set_xy(x0 + col_widths[0], row_y)
        pdf.multi_cell(col_widths[1], row_h / max(1, detail_lines),
                       name[:80], new_x=XPos.RIGHT, new_y=YPos.TOP)

        # Severity badge area
        _sev_badge(pdf, severity, x0 + col_widths[0] + col_widths[1], row_y + 1, col_widths[2] - 2, 5)

        # Status badge area
        _status_badge(pdf, status, x0 + col_widths[0] + col_widths[1] + col_widths[2], row_y + 1, col_widths[3] - 2, 5)

        # Detail text
        if detail:
            pdf.set_font("Helvetica", "", 6)
            pdf.set_text_color(*_C_MUTED)
            pdf.set_xy(x0 + sum(col_widths[:4]), row_y)
            pdf.multi_cell(col_widths[4], 4, detail[:200], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        cur_y = row_y + row_h

        # Remediation note
        if status == "fail" and remediation:
            pdf.set_xy(x0 + col_widths[0], cur_y)
            pdf.set_fill_color(248, 250, 252)
            pdf.set_draw_color(99, 102, 241)
            pdf.set_font("Helvetica", "I", 6)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(2, 0, "", border="L", fill=False, new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.set_xy(x0 + col_widths[0] + 3, cur_y)
            pdf.multi_cell(sum(col_widths[1:]) - 3, 4, f"Fix: {remediation[:300]}",
                           new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            cur_y = pdf.get_y()

        # Vendor CLI command
        if vendor_cmd:
            pdf.set_xy(x0 + col_widths[0], cur_y)
            pdf.set_fill_color(*_C_CMD_BG)
            pdf.set_font("Courier", "", 6)
            pdf.set_text_color(22, 101, 52)
            line_h = 4
            for line in vendor_cmd.splitlines():
                pdf.set_xy(x0 + col_widths[0] + 2, cur_y)
                pdf.cell(sum(col_widths[1:]) - 2, line_h, line[:100],
                         fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                cur_y += line_h

        # Manual check note
        if manual_note:
            pdf.set_xy(x0 + col_widths[0], cur_y)
            pdf.set_font("Helvetica", "I", 6)
            pdf.set_text_color(133, 77, 14)
            pdf.multi_cell(sum(col_widths[1:]), 4, f"Manual check: {manual_note[:300]}",
                           new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            cur_y = pdf.get_y()

        # Affected items
        if affected:
            pdf.set_xy(x0 + col_widths[0], cur_y)
            pdf.set_font("Courier", "", 5.5)
            pdf.set_text_color(*_C_MUTED)
            affected_str = ", ".join(str(a) for a in affected[:10])
            if len(affected) > 10:
                affected_str += f" ... (+{len(affected)-10} more)"
            pdf.cell(sum(col_widths[1:]), 4, affected_str, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            cur_y = pdf.get_y()

        # Row separator
        pdf.set_draw_color(*_C_BORDER)
        pdf.set_xy(x0, cur_y)
        pdf.cell(sum(col_widths), 0, "", border="B", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*_C_TEXT)
        pdf.ln(1)


def _write_manual_checks(pdf: FPDF, report: dict) -> None:
    manual_items = [f for f in report.get("findings", []) if f.get("status") == "manual_check"]
    if not manual_items:
        return

    pdf.add_page()
    _section_header(pdf, f"Manual Verification Checklist ({len(manual_items)} items)")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_C_MUTED)
    pdf.cell(0, 5, "The following items require human review and cannot be determined from static analysis.",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    for i, f in enumerate(manual_items, 1):
        if pdf.get_y() > pdf.h - 30:
            pdf.add_page()

        y0 = pdf.get_y()
        x0 = pdf.l_margin

        # Checkbox area
        pdf.set_fill_color(*_C_WHITE)
        pdf.set_draw_color(*_C_BORDER)
        pdf.rect(x0, y0 + 1, 5, 5, "FD")

        # Rule ID
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*_C_MANUAL)
        pdf.set_xy(x0 + 8, y0)
        pdf.cell(22, 7, _t(f.get("rule_id", "")), new_x=XPos.RIGHT, new_y=YPos.TOP)

        # Name
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_C_TEXT)
        pdf.set_xy(x0 + 32, y0)
        pdf.multi_cell(148, 7, _t(f.get("name", "")), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Manual note
        note = _t(f.get("manual_note") or "")
        if note:
            pdf.set_xy(x0 + 32, pdf.get_y())
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(*_C_MUTED)
            pdf.multi_cell(148, 5, note, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_draw_color(*_C_BORDER)
        pdf.set_xy(x0, pdf.get_y())
        pdf.cell(0, 0, "", border="B", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(3)
        pdf.set_text_color(*_C_TEXT)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_pdf(report: dict, output_path: Path | None = None) -> bytes:
    """Render *report* as a PDF and return the raw bytes.

    If *output_path* is given, the PDF is also written to that path.
    """
    pdf = _FireAuditPDF(report)
    pdf.add_page()

    # Title block (below header)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*_C_TEXT)
    device = report.get("device", {})
    hostname = device.get("hostname") or device.get("vendor", "Unknown")
    pdf.cell(0, 10, _t(f"Security Audit Report - {hostname}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_C_MUTED)
    pdf.cell(0, 6, _t(f"Generated by FireAudit  |  {report.get('generated_at', '')}"),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    _write_posture_banner(pdf, report)
    _write_device_info(pdf, report)
    _write_summary_stats(pdf, report)
    _write_framework_scores(pdf, report)

    if report.get("findings"):
        pdf.add_page()
        _write_findings(pdf, report)

    _write_manual_checks(pdf, report)

    raw = bytes(pdf.output())

    if output_path is not None:
        Path(output_path).write_bytes(raw)

    return raw
